//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/**
 * Request payload for the Copy block action on the Group
 * Detail block. Backed by the Copy Group modal in the view panel
 * footer.
 */
export type CopyGroupRequestBag = {
    /**
     * Gets or sets a value indicating whether descendant groups are
     * included in the copy. The Vue modal defaults this to
     * false, which is a deliberate flip from the WebForms
     * behavior (which defaulted to true).
     */
    includeChildGroups: boolean;

    /**
     * Gets or sets the IdKey (or integer Id) of the source group to
     * copy. The block resolves both forms via the Group service.
     */
    key?: string | null;
};
