//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";

/**
 * One row in the Location modal's Member tab dropdown source. Maps
 * a Group Member's family address to the underlying Location plus
 * the primary PersonAlias for the member, so the save flow can
 * stamp GroupLocation.GroupMemberPersonAliasId alongside
 * GroupLocation.LocationId. Mirrors WebForms
 * ddlMember rows at GroupDetail.ascx.cs:3525-3549.
 */
export type FamilyMemberLocationBag = {
    /**
     * Gets or sets the Guid of the underlying Location row.
     * Resolved server-side to Location.Id when writing
     * GroupLocation.LocationId.
     */
    locationGuid: Guid;

    /**
     * Gets or sets the primary PersonAlias.Guid for the
     * member who owns this family address. Resolved server-side to
     * PersonAlias.Id when writing
     * GroupLocation.GroupMemberPersonAliasId.
     */
    personAliasGuid: Guid;

    /**
     * Gets or sets the friendly dropdown text, formatted as
     * "{Member.FullName} {AddressType.Value} ({Address})"
     * per WebForms parity at GroupDetail.ascx.cs:3540-3543.
     */
    text?: string | null;
};
