//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { AppliesToAgeClassification } from "@Obsidian/Enums/Group/appliesToAgeClassification";
import { DueDateType } from "@Obsidian/Enums/Group/dueDateType";
import { Guid } from "@Obsidian/Types";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/**
 * Represents a single Group Requirement row in the Section 7 grid.
 * Used by both the read-only "From Group Type" grid and the editable
 * "Specific Group Requirements" grid. Scoped to per-group requirements.
 */
export type GroupRequirementBag = {
    /** Gets or sets a value indicating whether leaders are allowed to override the requirement. */
    allowLeadersToOverride: boolean;

    /** Gets or sets the age classification to which this requirement applies. */
    appliesToAgeClassification: AppliesToAgeClassification;

    /**
     * Gets or sets the data view that determines who the requirement
     * applies to. Null = applies to all members.
     */
    appliesToDataView?: ListItemBag | null;

    /**
     * Gets or sets the group attribute holding the due date when
     * DueDateType is GroupAttribute. ListItemBag.value is
     * the Attribute Guid.
     */
    dueDateAttribute?: ListItemBag | null;

    /**
     * Gets or sets the static due date when DueDateType is
     * ConfiguredDate.
     */
    dueDateStaticDate?: string | null;

    /**
     * Gets or sets the due date type sourced from the selected
     * GroupRequirementType. Drives which of the static date /
     * group attribute the modal renders.
     */
    dueDateType: DueDateType;

    /**
     * Gets or sets the group requirement type. ListItemBag.value
     * is the GroupRequirementType Guid.
     */
    groupRequirementType?: ListItemBag | null;

    /** Gets or sets the unique identifier of the group requirement. */
    guid: Guid;

    /**
     * Gets or sets a value indicating whether members must meet this
     * requirement before being added.
     */
    mustMeetRequirementToAddMember: boolean;

    /**
     * Gets or sets the group role this requirement applies to. Null
     * applies to all roles. ListItemBag.value is the
     * GroupTypeRole Guid.
     */
    role?: ListItemBag | null;
};
