//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupLocationPickerMode } from "@Obsidian/Enums/Group/groupLocationPickerMode";
import { RelationshipStrength } from "@Obsidian/Enums/Group/relationshipStrength";
import { ScheduleType } from "@Obsidian/Enums/Group/scheduleType";
import { Guid } from "@Obsidian/Types";
import { GroupMemberInheritedAttributeBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupMemberInheritedAttributeBag";
import { GroupRequirementTypeBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupRequirementTypeBag";
import { InheritedGroupRequirementBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/inheritedGroupRequirementBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/**
 * Per-GroupType options consumed by the edit panel. Returned by the
 * GetGroupTypeOptions block action when currentGroupTypeId
 * changes mid-edit (Q2 Approach B). Carries every flag, dropdown source,
 * and pin-by-group-type value the edit panel needs to reshape itself
 * when the GroupType changes. Also returned alongside the initial
 * Edit bag so the edit panel can render its first frame without
 * a second round-trip.
 */
export type GroupTypeOptionsBag = {
    /**
     * Gets or sets the localized term for the group administrator
     * (default: "Administrator"). Used as the label of the Group
     * Administrator picker.
     */
    administratorTerm?: string | null;

    /**
     * Gets or sets the bitmask of ScheduleType values the group
     * type permits. Drives which radio options render under Section 4
     * Stack 1.
     */
    allowedScheduleTypes: ScheduleType;

    /**
     * Gets or sets a value indicating whether the group type
     * permits group sync rules. Drives the Section 9 panel
     * visibility (combined with ADMINISTRATE on the group bag and
     * the presence of any existing syncs).
     * 
     * Mirrors `GroupType.AllowGroupSync`. The corresponding
     * WebForms gate at `GroupDetail.ascx.cs:2195` uses
     * ADMINISTRATE on the <em>GroupType</em>, with a sticky
     * override at `:2002` that keeps the panel visible for an
     * existing group when the user has ADMINISTRATE on the
     * <em>Group</em>. The Obsidian impl simplifies both into a
     * single ADMINISTRATE-on-the-Group check on the group bag,
     * which is the dominant code path under standard Rock auth
     * (Group auth inherits from GroupType) and avoids the
     * ViewState stickiness that has no analog here.
     */
    allowGroupSync: boolean;

    /**
     * Gets or sets a value indicating whether more than one
     * GroupLocation may be added to groups of this type.
     * Drives the Section 4 Stack 2 grid's Add-button visibility per
     * WebForms parity at GroupDetail.ascx.cs:3872: the Add
     * button is shown only when
     * allowMultipleLocations || locations.length == 0.
     * Mirrors GroupType.AllowMultipleLocations.
     */
    allowMultipleLocations: boolean;

    /**
     * Gets or sets a value indicating whether the group type
     * permits per-group attribute definitions for members. Drives
     * the Section 6 panel-visibility gate (along with the per-user
     * ADMINISTRATE flag on the group bag) per WebForms parity at
     * GroupDetail.ascx.cs:2001-2004. Mirrors
     * GroupType.AllowSpecificGroupMemberAttributes.
     */
    allowSpecificGroupMemberAttributes: boolean;

    /**
     * Gets or sets a value indicating whether the group type
     * permits per-group member workflow triggers. Drives the
     * Section 10 panel visibility (combined with the presence of
     * any legacy triggers) per WebForms parity at
     * GroupDetail.ascx.cs:2198. Mirrors
     * GroupType.AllowSpecificGroupMemberWorkflows.
     */
    allowSpecificGroupMemberWorkflows: boolean;

    /**
     * Gets or sets a value indicating whether per-location schedule
     * configuration is enabled. Drives the visibility of the
     * Schedule(s) multi-picker in the Location modal. Mirrors
     * GroupType.EnableLocationSchedules.
     */
    enableLocationSchedules: boolean;

    /**
     * Gets or sets a value indicating whether the group type
     * permits per-group group requirements. Drives the Section 7
     * "Specific Group Requirements" Add-button visibility plus the
     * editable-grid wrapper visibility per WebForms parity at
     * GroupDetail.ascx.cs:4554. Mirrors
     * GroupType.EnableSpecificGroupRequirements.
     */
    enableSpecificGroupRequirements: boolean;

    /**
     * Gets or sets the date-typed group attribute dropdown options
     * for the Section 7 modal's Due Date Attribute conditional
     * well. ListItemBag.value is the Attribute Guid. Sourced
     * from the inherited attribute chain filtered to
     * Date / DateTime field types.
     */
    groupAttributeOptions?: ListItemBag[] | null;

    /**
     * Gets or sets the group requirement type dropdown options for
     * the Section 7 modal. Each entry carries the type's
     * Rock.Model.DueDateType so the modal's DueDate
     * conditional well reacts to the selection without an extra
     * round-trip.
     */
    groupRequirementTypeOptions?: GroupRequirementTypeBag[] | null;

    /**
     * Gets or sets the group role dropdown options for the
     * Section 7 / 9 / 10 modals. ListItemBag.value is the
     * GroupTypeRole Guid; ListItemBag.text is the role name.
     * Sourced from GroupType.Roles on the active group type
     * (no inheritance walk per WebForms parity).
     */
    groupRoleOptions?: ListItemBag[] | null;

    /**
     * Gets or sets the icon CSS class sourced from the group type
     * (e.g., ti ti-users-group). Drives the panel header icon
     * when the GroupType changes mid-edit.
     */
    iconCssClass?: string | null;

    /**
     * Gets or sets the list of allowed inactive reason
     * DefinedValue rows for this group type, sourced from
     * GroupTypeService.GetInactiveReasonsForGroupType. Empty
     * list when GroupType.EnableInactiveReason is false.
     */
    inactiveReasons?: ListItemBag[] | null;

    /**
     * Gets or sets the read-only inherited group-requirement rows
     * for the current group type. Walks the
     * InheritedGroupTypeId chain, mirroring the inheritance
     * pattern used by InheritedMemberAttributes on
     * Rock.ViewModels.Blocks.Group.GroupDetail.GroupBag. Each row carries its own
     * InheritedFromGroupTypeName / InheritedFromGroupTypeUrl
     * so the grid can render per-row "(Inherited from {link})"
     * cells. Empty when no ancestor group type defines a
     * requirement.
     */
    inheritedGroupRequirements?: InheritedGroupRequirementBag[] | null;

    /**
     * Gets or sets the inherited group-member attribute definitions
     * for the active group type. Walks the
     * GroupType.InheritedGroupTypeId chain server-side and
     * emits each attribute with the immediate ancestor's name + URL
     * for the Section 6 "Inherited Attributes" grid. Empty when the
     * chain yields no inherited member attributes.
     */
    inheritedMemberAttributes?: GroupMemberInheritedAttributeBag[] | null;

    /**
     * Gets or sets a value indicating whether the Group Administrator
     * picker renders. Mirrors GroupType.ShowAdministrator.
     */
    isAdministratorVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Chat section
     * renders. Combines ChatHelper.IsChatEnabled (the system
     * flag) with GroupType.IsChatAllowed.
     */
    isChatSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Who Can Check-in
     * radio renders. Mirrors GroupType.TakesAttendance.
     */
    isCheckInRequirementsVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Coordinator
     * Notifications checkboxes render. Mirrors
     * GroupType.IsSchedulingEnabled.
     */
    isCoordinatorNotificationsVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Group Capacity field
     * is required. Mirrors GroupType.IsCapacityRequired.
     */
    isGroupCapacityRequired: boolean;

    /**
     * Gets or sets a value indicating whether the Group Capacity field
     * renders. Mirrors GroupType.GroupCapacityRule != None.
     */
    isGroupCapacityVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Member Record Source
     * picker renders. Mirrors
     * GroupType.AllowGroupSpecificRecordSource.
     */
    isGroupSpecificRecordSourceVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Inactive Reason
     * dropdown is required. Mirrors
     * GroupType.RequiresInactiveReason.
     */
    isInactiveReasonRequired: boolean;

    /**
     * Gets or sets a value indicating whether the Inactive Reason
     * dropdown renders inside the Inactive flow conditional well.
     * Mirrors GroupType.EnableInactiveReason.
     */
    isInactiveReasonVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Peer Network override
     * stack renders inside the General section. Mirrors
     * GroupType.IsPeerNetworkEnabled.
     */
    isPeerNetworkSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the RSVP section
     * renders. Mirrors GroupType.EnableRSVP.
     */
    isRsvpSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Confirmation Behavior
     * dropdown renders within the Member Scheduling stack. Mirrors
     * GroupType.IsSchedulingEnabled.
     */
    isScheduleConfirmationLogicVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Schedule Coordinator
     * person picker renders. Mirrors GroupType.IsSchedulingEnabled.
     */
    isScheduleCoordinatorVisible: boolean;

    /**
     * Gets or sets a value indicating whether scheduling is enabled
     * at the group-type level. Drives the master switch for the
     * Member Scheduling stack.
     */
    isSchedulingEnabled: boolean;

    /**
     * Gets or sets a value indicating whether the Scheduling section's
     * "Overall Group Schedule" stack renders. True when any
     * GroupType.AllowedScheduleTypes flag is set.
     */
    isSchedulingSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Status defined-value
     * picker renders. Mirrors
     * GroupType.GroupStatusDefinedTypeId.HasValue.
     */
    isStatusVisible: boolean;

    /**
     * Gets or sets the group-type's leader-to-leader multiplier as a
     * 0-1 decimal. Rendered as the placeholder ("inherited") on the
     * override input.
     */
    leaderToLeaderMultiplierDefault: number;

    /**
     * Gets or sets the group-type's leader-to-non-leader multiplier
     * as a 0-1 decimal. Rendered as the placeholder ("inherited") on
     * the override input.
     */
    leaderToNonLeaderMultiplierDefault: number;

    /**
     * Gets or sets the location-selection mode for the group type.
     * Drives the Section 4 Stack 2 visibility (hidden when
     * None) plus the
     * &lt;LocationPicker&gt;'s allowedPickerModes
     * inside the Location modal.
     */
    locationSelectionMode: GroupLocationPickerMode;

    /**
     * Gets or sets the Location Type DefinedValue dropdown options
     * scoped to GroupType.LocationTypeValues. Empty when the
     * group type configures no location types.
     * ListItemBag.value is the DefinedValue Guid;
     * ListItemBag.text is the display value.
     */
    locationTypeValueOptions?: ListItemBag[] | null;

    /**
     * Gets or sets the map-style DefinedValue Guid sourced from
     * the MapStyle block attribute. Carried on this cascade
     * bag so the LocationPicker inside the modal can render the
     * admin's configured map style without an extra round-trip on
     * GroupType change. Mirrors WebForms parity at
     * GroupDetail.ascx.cs:3567.
     */
    mapStyleValueGuid?: Guid | null;

    /**
     * Gets or sets the group-type's non-leader-to-leader multiplier
     * as a 0-1 decimal. Rendered as the placeholder ("inherited") on
     * the override input.
     */
    nonLeaderToLeaderMultiplierDefault: number;

    /**
     * Gets or sets the group-type's non-leader-to-non-leader
     * multiplier as a 0-1 decimal. Rendered as the placeholder
     * ("inherited") on the override input.
     */
    nonLeaderToNonLeaderMultiplierDefault: number;

    /**
     * Gets or sets the group-type's relationship-growth-enabled
     * default, used when the group has no override.
     */
    relationshipGrowthEnabledDefault: boolean;

    /**
     * Gets or sets the group-type's relationship strength default,
     * shown as the radio's resolved value when the group has no
     * override. Falls back to None when the group type has
     * no value set.
     */
    relationshipStrengthDefault: RelationshipStrength;

    /**
     * Gets or sets a value indicating whether selecting a Campus is
     * required when saving a group of this type. Mirrors
     * GroupType.GroupsRequireCampus.
     */
    requiresCampus: boolean;

    /**
     * Gets or sets the group-type's pinned RSVP reminder offset days.
     * Non-null means the group-type pins this value and the per-group
     * override is read-only. Null means the group can override.
     */
    rsvpReminderOffsetDays?: number | null;

    /**
     * Gets or sets the group-type's pinned RSVP reminder system
     * communication. Non-null means the group-type pins this value
     * and the per-group override is read-only; the
     * ListItemBag.text is shown as the readonly label.
     * Null means the group can override.
     */
    rsvpReminderSystemCommunication?: ListItemBag | null;

    /**
     * Gets or sets the list of system communications in the RSVP
     * Confirmation category. Populates the per-group dropdown when
     * the group-type does not pin the value.
     */
    rsvpSystemCommunicationOptions?: ListItemBag[] | null;

    /**
     * Gets or sets the list of DefinedValue rows under
     * GroupType.GroupStatusDefinedType, used to populate the
     * Status dropdown. Empty list when the group type does not
     * configure a status defined type.
     */
    statusValues?: ListItemBag[] | null;

    /**
     * Gets or sets the system communication dropdown options for
     * the Section 9 Welcome / Exit dropdowns.
     * ListItemBag.value is the SystemCommunication Guid;
     * ListItemBag.text is the communication title. Drives
     * both Welcome and Exit dropdowns in the Sync modal.
     */
    systemCommunicationOptions?: ListItemBag[] | null;
};
