//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/**
 * Per-block options consumed by the Group Detail Vue layer. Carries
 * the visibility flags driving the Group Tools card and the
 * action-button visibility helpers used by the panel footer. The
 * outbound URLs themselves live on DetailBlockBox.NavigationUrls
 * (each containing the literal ((Key)) placeholder per Q4 /
 * IdKey policy).
 */
export type GroupDetailOptionsBag = {
    /**
     * Gets or sets a value indicating whether the Archive button is
     * visible in place of Delete. Mirrors the WebForms condition:
     * !IsSystem &amp;&amp; !IsArchived &amp;&amp; EDIT &amp;&amp;
     * EnableGroupHistory &amp;&amp; (groupHistorical || groupMemberHistorical
     * rows exist).
     */
    isArchiveVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Attendance row
     * renders in the Group Tools card. Combines the URL presence with
     * GroupType.TakesAttendance.
     */
    isAttendanceVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Copy button shows
     * in the panel footer. Combines the ShowCopyButton block
     * attribute with EDIT auth.
     */
    isCopyButtonShown: boolean;

    /**
     * Gets or sets a value indicating whether the Delete button is
     * shown in the panel footer. Mirrors the inverse of the Archive
     * visibility condition (system, archived, no auth, or
     * archive-replacement above all hide Delete).
     */
    isDeleteVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Fundraising Progress
     * row renders. Combines the URL presence with the group type
     * being a Fundraising Opportunity (or descendant).
     */
    isFundraisingVisible: boolean;

    /**
     * Gets or sets a value indicating whether the History row
     * renders. Combines the URL presence with
     * GroupType.EnableGroupHistory.
     */
    isHistoryVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Interactive Map row
     * renders. Driven solely by URL presence; map renders for any
     * group type when configured.
     */
    isMapVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Placement row
     * renders. Driven by URL presence and a non-null group type.
     */
    isPlacementVisible: boolean;

    /**
     * Gets or sets a value indicating whether the RSVP row renders.
     * Combines the URL presence with GroupType.EnableRSVP.
     */
    isRsvpVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Scheduler row
     * renders. Combines the URL presence with
     * GroupType.IsSchedulingEnabled.
     */
    isSchedulerVisible: boolean;

    /**
     * Gets or sets a value indicating whether the tag list renders in
     * the subheader. Combines the EnableGroupTags block
     * attribute with GroupType.EnableGroupTag.
     */
    isTagListShown: boolean;

    /**
     * Gets or sets a value indicating whether the Delete button is
     * suppressed because Archive replaces it (i.e., GroupHistory is
     * enabled and at least one history row exists).
     */
    shouldShowArchiveInsteadOfDelete: boolean;
};
