//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupLocationPickerMode } from "@Obsidian/Enums/Group/groupLocationPickerMode";
import { Guid } from "@Obsidian/Types";

/**
 * One Meeting Location card on the right rail of the Group Detail
 * view panel. Each GroupLocation on the group renders as one
 * instance of this bag in GroupBag.MeetingLocations. The Vue
 * layer renders the variants (Address / Point / Polygon / GroupMember)
 * from the Rock.ViewModels.Blocks.Group.GroupDetail.GroupMeetingLocationBag.Mode field. See Phase 2 spec section C2 for
 * the full field contract and Q2.5 for the WKT pass-through shape of
 * Rock.ViewModels.Blocks.Group.GroupDetail.GroupMeetingLocationBag.MapData.
 */
export type GroupMeetingLocationBag = {
    /**
     * Gets or sets the multi-line formatted address text for the
     * card. Null for polygon-style locations (which intentionally
     * render no address) and null when the
     * ShowLocationAddresses block attribute is false (per
     * Q2.6 — suppresses address text uniformly across every card
     * variant). Address-style cards source this from
     * Location.FormattedAddress; member-address cards source
     * from the family's home address.
     */
    address?: string | null;

    /**
     * Gets or sets the GroupLocation.Guid for the row backing
     * this card. Stable per-render identifier used as the Vue
     * v-for key on the location list. Phase 6's editing modal
     * will use this Guid to identify rows in the in-progress state
     * collection (matching the WebForms hfGroupLocationGuid
     * pattern at research/webforms/07-locations-and-schedules.md);
     * new unsaved rows will be created with Guid.NewGuid().
     */
    guid: Guid;

    /**
     * Gets or sets the raw Well-Known Text (WKT) geometry that the
     * Vue map renderer passes through wellKnownToCoordinates
     * from @Obsidian/Utility/geo. Format mirrors what
     * Location.GeoPoint / Location.GeoFence store as
     * DbGeography (e.g., POINT(-112.130946 33.600114)
     * or POLYGON((-112.157058 33.598563, ...))). Empty
     * string when the location has no geo data; the map still
     * instantiates but no shape renders.
     */
    mapData?: string | null;

    /**
     * Gets or sets the URL the hover-expand button (or full-card tap
     * on touch) navigates to. Per Q2.3 every card on a given group
     * shares the same group-level URL pointing at
     * GroupMapPage?GroupId={IdKey}; the field is per-card on
     * the bag for forward-compat in case the destination later
     * supports a per-location parameter.
     */
    mapUrl?: string | null;

    /**
     * Gets or sets the location-picker mode classification used to
     * drive the per-card render variant on the Vue side. Address /
     * Point / Polygon / GroupMember each render slightly differently
     * (marker vs polygon, address text source, etc.). Mirrors the
     * underlying GroupLocation classification described in
     * research/webforms/07-locations-and-schedules.md.
     */
    mode: GroupLocationPickerMode;

    /**
     * Gets or sets the optional display name from
     * GroupLocation.Location.Name. May be null when the
     * location has no Name (e.g., address-only or polygon-only
     * locations); the Vue layer handles the null gracefully.
     */
    name?: string | null;

    /**
     * Gets or sets the friendly schedule text (e.g.,
     * "Saturday 4:00pm") sourced from the first associated
     * schedule's FriendlyScheduleText. Null when no schedule
     * is attached to this GroupLocation; the row hides in
     * that case.
     */
    scheduleText?: string | null;
};
