//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/**
 * Represents a single Group Sync row in the Section 9 grid.
 * Mirrors the WebForms GroupSyncViewModel shape at
 * GroupDetail.ascx.cs:5115 in bag form.
 */
export type GroupSyncBag = {
    /**
     * Gets or sets a value indicating whether a Rock login account
     * should be created for synced members that do not yet have one.
     */
    addUserAccountsDuringSync: boolean;

    /**
     * Gets or sets the exit system communication sent on removal.
     * ListItemBag.value is the SystemCommunication Guid.
     */
    exitSystemCommunication?: ListItemBag | null;

    /**
     * Gets or sets the role members synced into this group are
     * assigned. ListItemBag.value is the GroupTypeRole Guid;
     * ListItemBag.text is the role name.
     */
    groupTypeRole?: ListItemBag | null;

    /** Gets or sets the unique identifier of the group sync. */
    guid: Guid;

    /**
     * Gets or sets the date/time of the last successful sync run.
     * Display only.
     */
    lastRefreshDateTime?: string | null;

    /**
     * Gets or sets the interval (in minutes) between sync runs.
     */
    scheduleIntervalMinutes?: number | null;

    /**
     * Gets or sets the data view that identifies group members.
     * ListItemBag.value is the DataView Guid.
     */
    syncDataView?: ListItemBag | null;

    /**
     * Gets or sets the welcome system communication sent on add.
     * ListItemBag.value is the SystemCommunication Guid.
     */
    welcomeSystemCommunication?: ListItemBag | null;
};
