//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupMemberStatus } from "@Obsidian/Enums/Group/groupMemberStatus";
import { GroupMemberWorkflowTriggerType } from "@Obsidian/Enums/Group/groupMemberWorkflowTriggerType";
import { Guid } from "@Obsidian/Types";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/**
 * Represents a single Group Member Workflow Trigger row in the
 * Section 10 grid. The pipe-delimited 7-tuple TypeQualifier
 * persisted on the entity is decomposed into individual typed
 * fields here so the Vue layer never touches the raw qualifier
 * string.
 */
export type GroupMemberWorkflowTriggerBag = {
    /** Gets or sets the "from" role qualifier Guid. */
    fromRoleGuid?: Guid | null;

    /** Gets or sets the "from" status qualifier. */
    fromStatus?: GroupMemberStatus | null;

    /** Gets or sets the unique identifier of the workflow trigger. */
    guid: Guid;

    /** Gets or sets a value indicating whether the trigger is active. */
    isActive: boolean;

    /** Gets or sets the user-facing name of the workflow trigger. */
    name?: string | null;

    /**
     * Gets or sets a value indicating whether the placement workflow
     * requires a note.
     */
    requireNoteOnPlacement: boolean;

    /**
     * Gets or sets a value indicating whether the placement workflow
     * shows a note entry field.
     */
    showNoteOnPlacement: boolean;

    /** Gets or sets the "to" role qualifier Guid. */
    toRoleGuid?: Guid | null;

    /** Gets or sets the "to" status qualifier. */
    toStatus?: GroupMemberStatus | null;

    /**
     * Gets or sets a value indicating whether the workflow fires only
     * on the member's first attendance.
     */
    triggerOnFirstAttendance: boolean;

    /** Gets or sets the trigger type. */
    triggerType: GroupMemberWorkflowTriggerType;

    /**
     * Gets or sets the workflow type to start when the trigger fires.
     * ListItemBag.value is the WorkflowType Guid.
     */
    workflowType?: ListItemBag | null;
};
