//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupLocationPickerMode } from "@Obsidian/Enums/Group/groupLocationPickerMode";
import { RelationshipStrength } from "@Obsidian/Enums/Group/relationshipStrength";
import { ScheduleType } from "@Obsidian/Enums/Group/scheduleType";
import { Guid } from "@Obsidian/Types";
import { GroupMemberInheritedAttributeBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupMemberInheritedAttributeBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/**
 * Per-GroupType options consumed by the edit panel. Returned by the
 * GetGroupTypeOptions block action when currentGroupTypeId
 * changes mid-edit (Q2 Approach B). Carries every flag, dropdown source,
 * and pin-by-group-type value the edit panel needs to reshape itself
 * when the GroupType changes. Also returned alongside the initial
 * Edit bag so the edit panel can render its first frame without
 * a second round-trip.
 */
export type GroupTypeOptionsBag = {
    /**
     * Gets or sets the localized term for the group administrator
     * (default: "Administrator"). Used as the label of the Group
     * Administrator picker.
     */
    administratorTerm?: string | null;

    /**
     * Gets or sets the bitmask of ScheduleType values the group
     * type permits. Drives which radio options render under Section 4
     * Stack 1.
     */
    allowedScheduleTypes: ScheduleType;

    /**
     * Gets or sets a value indicating whether per-location schedule
     * configuration is enabled. Phase 6 surface; surfaced now to
     * complete the cascade payload. Mirrors
     * GroupType.EnableLocationSchedules.
     */
    enableLocationSchedules: boolean;

    /**
     * Gets or sets the icon CSS class sourced from the group type
     * (e.g., ti ti-users-group). Drives the panel header icon
     * when the GroupType changes mid-edit.
     */
    iconCssClass?: string | null;

    /**
     * Gets or sets the list of allowed inactive reason
     * DefinedValue rows for this group type, sourced from
     * GroupTypeService.GetInactiveReasonsForGroupType. Empty
     * list when GroupType.EnableInactiveReason is false.
     */
    inactiveReasons?: ListItemBag[] | null;

    /**
     * Gets or sets the inherited group-member attribute definitions
     * for the active group type. Walks the
     * GroupType.InheritedGroupTypeId chain server-side and
     * emits each attribute with the immediate ancestor's name + URL
     * for the Section 6 "Inherited Attributes" grid. Empty when the
     * chain yields no inherited member attributes.
     */
    inheritedMemberAttributes?: GroupMemberInheritedAttributeBag[] | null;

    /**
     * Gets or sets a value indicating whether the Group Administrator
     * picker renders. Mirrors GroupType.ShowAdministrator.
     */
    isAdministratorVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Chat section
     * renders. Combines ChatHelper.IsChatEnabled (the system
     * flag) with GroupType.IsChatAllowed.
     */
    isChatSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Who Can Check-in
     * radio renders. Mirrors GroupType.TakesAttendance.
     */
    isCheckInRequirementsVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Coordinator
     * Notifications checkboxes render. Mirrors
     * GroupType.IsSchedulingEnabled.
     */
    isCoordinatorNotificationsVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Group Capacity field
     * is required. Mirrors GroupType.IsCapacityRequired.
     */
    isGroupCapacityRequired: boolean;

    /**
     * Gets or sets a value indicating whether the Group Capacity field
     * renders. Mirrors GroupType.GroupCapacityRule != None.
     */
    isGroupCapacityVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Member Record Source
     * picker renders. Mirrors
     * GroupType.AllowGroupSpecificRecordSource.
     */
    isGroupSpecificRecordSourceVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Inactive Reason
     * dropdown is required. Mirrors
     * GroupType.RequiresInactiveReason.
     */
    isInactiveReasonRequired: boolean;

    /**
     * Gets or sets a value indicating whether the Inactive Reason
     * dropdown renders inside the Inactive flow conditional well.
     * Mirrors GroupType.EnableInactiveReason.
     */
    isInactiveReasonVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Peer Network override
     * stack renders inside the General section. Mirrors
     * GroupType.IsPeerNetworkEnabled.
     */
    isPeerNetworkSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the RSVP section
     * renders. Mirrors GroupType.EnableRSVP.
     */
    isRsvpSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Confirmation Behavior
     * dropdown renders within the Member Scheduling stack. Mirrors
     * GroupType.IsSchedulingEnabled.
     */
    isScheduleConfirmationLogicVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Schedule Coordinator
     * person picker renders. Mirrors GroupType.IsSchedulingEnabled.
     */
    isScheduleCoordinatorVisible: boolean;

    /**
     * Gets or sets a value indicating whether scheduling is enabled
     * at the group-type level. Drives the master switch for the
     * Member Scheduling stack.
     */
    isSchedulingEnabled: boolean;

    /**
     * Gets or sets a value indicating whether the Scheduling section's
     * "Overall Group Schedule" stack renders. True when any
     * GroupType.AllowedScheduleTypes flag is set.
     */
    isSchedulingSectionVisible: boolean;

    /**
     * Gets or sets a value indicating whether the Status defined-value
     * picker renders. Mirrors
     * GroupType.GroupStatusDefinedTypeId.HasValue.
     */
    isStatusVisible: boolean;

    /**
     * Gets or sets the group-type's leader-to-leader multiplier as a
     * 0-1 decimal. Rendered as the placeholder ("inherited") on the
     * override input.
     */
    leaderToLeaderMultiplierDefault: number;

    /**
     * Gets or sets the group-type's leader-to-non-leader multiplier
     * as a 0-1 decimal. Rendered as the placeholder ("inherited") on
     * the override input.
     */
    leaderToNonLeaderMultiplierDefault: number;

    /**
     * Gets or sets the location-selection mode for the group type.
     * Phase 6 will use this when wiring up Section 4 Stack 2 (the
     * Locations grid + dialog); surfaced now so the cascade payload is
     * complete and Phase 6 does not re-fetch.
     */
    locationSelectionMode: GroupLocationPickerMode;

    /**
     * Gets or sets the group-type's non-leader-to-leader multiplier
     * as a 0-1 decimal. Rendered as the placeholder ("inherited") on
     * the override input.
     */
    nonLeaderToLeaderMultiplierDefault: number;

    /**
     * Gets or sets the group-type's non-leader-to-non-leader
     * multiplier as a 0-1 decimal. Rendered as the placeholder
     * ("inherited") on the override input.
     */
    nonLeaderToNonLeaderMultiplierDefault: number;

    /**
     * Gets or sets the group-type's relationship-growth-enabled
     * default, used when the group has no override.
     */
    relationshipGrowthEnabledDefault: boolean;

    /**
     * Gets or sets the group-type's relationship strength default,
     * shown as the radio's resolved value when the group has no
     * override. Falls back to None when the group type has
     * no value set.
     */
    relationshipStrengthDefault: RelationshipStrength;

    /**
     * Gets or sets a value indicating whether selecting a Campus is
     * required when saving a group of this type. Mirrors
     * GroupType.GroupsRequireCampus.
     */
    requiresCampus: boolean;

    /**
     * Gets or sets the group-type's pinned RSVP reminder offset days.
     * Non-null means the group-type pins this value and the per-group
     * override is read-only. Null means the group can override.
     */
    rsvpReminderOffsetDays?: number | null;

    /**
     * Gets or sets the group-type's pinned RSVP reminder system
     * communication. Non-null means the group-type pins this value
     * and the per-group override is read-only. Null means the group
     * can override.
     */
    rsvpReminderSystemCommunicationGuid?: Guid | null;

    /**
     * Gets or sets the list of DefinedValue rows under
     * GroupType.GroupStatusDefinedType, used to populate the
     * Status dropdown. Empty list when the group type does not
     * configure a status defined type.
     */
    statusValues?: ListItemBag[] | null;
};
