//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupLocationPickerMode } from "@Obsidian/Enums/Group/groupLocationPickerMode";
import { Guid } from "@Obsidian/Types";
import { GroupLocationScheduleConfigBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupLocationScheduleConfigBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/**
 * Represents a single editable Group Location row in the Section 4
 * Stack 2 grid. Mirrors WebForms GroupLocationsState at
 * GroupDetail.ascx.cs:3525-3848 in bag form, with the
 * LocationPicker emit shape locked per Q6.9
 * (Rock.ViewModels.Blocks.Group.GroupDetail.GroupLocationStateBag.SelectedLocation + Rock.ViewModels.Blocks.Group.GroupDetail.GroupLocationStateBag.SelectedLocationMode
 * discriminator) so server-side
 * LocationService resolution happens once at save time.
 * Active schedules only per Q6.3; inactive schedules are reconciled
 * server-side via DB load + union at save time.
 */
export type GroupLocationStateBag = {
    /**
     * Gets or sets the Location Type DefinedValue Guid scoped to
     * GroupType.LocationTypeValues. Resolved server-side to
     * GroupLocation.GroupLocationTypeValueId.
     */
    groupLocationTypeValueGuid?: Guid | null;

    /**
     * Gets or sets the friendly name of the selected location type,
     * used by the grid's Type column without a refetch.
     */
    groupLocationTypeValueName?: string | null;

    /**
     * Gets or sets the PersonAlias Guid for the family member who
     * owns this location. Non-null when the row was added via the
     * Member tab; drives the Edit-mode default tab inference per
     * Q6.13. Resolved server-side to
     * GroupLocation.GroupMemberPersonAliasId.
     */
    groupMemberPersonAliasGuid?: Guid | null;

    /**
     * Gets or sets the unique identifier of the group location.
     * New rows arrive with System.Guid.Empty; the save flow
     * assigns a fresh Guid before persisting.
     */
    guid: Guid;

    /**
     * Gets or sets the optional location description (rendered as a
     * secondary cell or hover tooltip; not required by the design).
     */
    locationDescription?: string | null;

    /**
     * Gets or sets the friendly text used to render the Location
     * column in the grid. Server-side build pulls
     * Location.ToString() or the formatted family-member
     * label so the grid never needs to refetch.
     */
    locationName?: string | null;

    /**
     * Gets or sets the per-schedule capacity matrix entries (one
     * row per selected schedule). Persisted as
     * GroupLocationScheduleConfig rows owned by the
     * containing GroupLocation.
     */
    scheduleConfigs?: GroupLocationScheduleConfigBag[] | null;

    /**
     * Gets or sets the active schedules attached to this
     * GroupLocation. ListItemBag.value is the
     * Schedule Guid; ListItemBag.text is the schedule's
     * friendly name. Inactive schedules are excluded from the bag
     * round-trip per Q6.3 and reconciled server-side.
     */
    schedules?: ListItemBag[] | null;

    /**
     * Gets or sets the raw picker emit. The runtime shape is
     * determined by Rock.ViewModels.Blocks.Group.GroupDetail.GroupLocationStateBag.SelectedLocationMode per Q6.9:
     * Rock.ViewModels.Utility.ListItemBag when Named or GroupMember (a
     * Rock.ViewModels.Blocks.Group.GroupDetail.FamilyMemberLocationBag.LocationGuid wrapper);
     * Rock.ViewModels.Controls.AddressControlBag when
     * Address; a Well-Known Text string when Point or Polygon.
     * Typed as System.Object so System.Text.Json can
     * round-trip the heterogeneous shape; the server-side resolver
     * branches on the discriminator and casts.
     */
    selectedLocation?: unknown;

    /**
     * Gets or sets the discriminator describing how
     * Rock.ViewModels.Blocks.Group.GroupDetail.GroupLocationStateBag.SelectedLocation was emitted by the
     * &lt;LocationPicker&gt; or the Member-tab dropdown.
     * Drives the server-side ResolveLocationFromBag branch.
     */
    selectedLocationMode: GroupLocationPickerMode;
};
