//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { RelationshipStrength } from "@Obsidian/Enums/Group/relationshipStrength";
import { GroupAdministratorBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupAdministratorBag";
import { GroupDetailGroupTypeBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupDetailGroupTypeBag";
import { GroupLinkagesBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupLinkagesBag";
import { GroupMeetingLocationBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/groupMeetingLocationBag";
import { ParentGroupBag } from "@Obsidian/ViewModels/Blocks/Group/GroupDetail/parentGroupBag";
import { PublicAttributeBag } from "@Obsidian/ViewModels/Utility/publicAttributeBag";

/**
 * The bag returned by the Group Detail block. Phase 1 ships the
 * view-mode fields. Phase 2 extends this bag with edit-mode scalar
 * fields, GroupType cascade options, peer-network overrides, RSVP /
 * Scheduling / Chat sections, and the new Group.PhotoId-driven
 * uploader fields.
 */
export type GroupBag = {
    /**
     * Gets or sets the group administrator reference. Null when no
     * administrator is set or when GroupType.ShowAdministrator
     * is false; the row is hidden in either case.
     */
    administrator?: GroupAdministratorBag | null;

    /** Gets or sets the attributes. */
    attributes?: Record<string, PublicAttributeBag> | null;

    /** Gets or sets the attribute values. */
    attributeValues?: Record<string, string> | null;

    /**
     * Gets or sets the campus name. Null when the group has no campus
     * assigned, which hides the campus chip in the header.
     */
    campusName?: string | null;

    /**
     * Gets or sets a value indicating whether the current user has
     * ADMINISTRATE auth on the group. Drives the Security button.
     */
    canAdministrate: boolean;

    /**
     * Gets or sets a value indicating whether the current user has
     * EDIT auth on the group. Drives Edit / Delete / Archive / Copy
     * visibility.
     */
    canEdit: boolean;

    /**
     * Gets or sets the group's description text rendered below the
     * image in the Overview card.
     */
    description?: string | null;

    /**
     * Gets or sets the group's capacity. Null when not configured,
     * which hides the row.
     */
    groupCapacity?: number | null;

    /**
     * Gets or sets the group type reference rendered as a chip in
     * the panel header. Rock.ViewModels.Blocks.Group.GroupDetail.GroupDetailGroupTypeBag.Url
     * is null when the current user lacks ADMINISTRATE on the group
     * type; the Vue layer renders the chip as plain text in that
     * case.
     */
    groupType?: GroupDetailGroupTypeBag | null;

    /**
     * Gets or sets a value indicating whether the group has any child
     * groups. Drives whether the Vue layer prompts the user to choose
     * between archiving the group alone or cascading the archive to
     * descendants. Mirrors the WebForms btnArchive_Click
     * children check at GroupDetail.ascx.cs:641.
     */
    hasChildGroups: boolean;

    /**
     * Gets or sets the icon CSS class sourced from the group type
     * (e.g., ti ti-users-group) and used in the panel header.
     */
    iconCssClass?: string | null;

    /** Gets or sets the identifier key of this entity. */
    idKey?: string | null;

    /** Gets or sets a value indicating whether the group is active. */
    isActive: boolean;

    /**
     * Gets or sets a value indicating whether the group is archived.
     * Archived groups hide the Delete button.
     */
    isArchived: boolean;

    /**
     * Gets or sets a value indicating whether the group is publicly
     * visible. Drives the Public chip in the subheader.
     */
    isPublic: boolean;

    /**
     * Gets or sets a value indicating whether the group is a system
     * group. System groups suppress Edit / Delete / Archive.
     */
    isSystem: boolean;

    /**
     * Gets or sets the linkages section content (registrations, event
     * item occurrences, content items). Null when the group has no
     * linkages of any kind, which omits the section entirely.
     */
    linkages?: GroupLinkagesBag | null;

    /**
     * Gets or sets the per-GroupLocation meeting location
     * cards rendered on the right rail of the View panel. Always
     * emitted; the Vue layer uses a v-if on
     * length > 0 to omit the entire card when the group
     * has no locations. Each entry renders as one 16:9 map card with
     * optional address and schedule below.
     */
    meetingLocations?: GroupMeetingLocationBag[] | null;

    /** Gets or sets the friendly name of the group. */
    name?: string | null;

    /**
     * Gets or sets the parent group reference. Null when the group
     * has no parent; the row is hidden in that case.
     */
    parentGroup?: ParentGroupBag | null;

    /**
     * Gets or sets the URL of the 16:9 hero image at the top of the
     * Overview card, populated from Group.PhotoUrl (which
     * resolves Group.PhotoId through FileUrlHelper).
     * Null when the group has no photo set; the Vue layer omits the
     * hero region entirely in that case (no placeholder, per design).
     */
    photoUrl?: string | null;

    /**
     * Gets or sets the effective relationship strength for the
     * subheader chip: the group's override falling back to the group
     * type default. Null when the group type lacks peer-network
     * support (chip hides) or when the stored integer does not map
     * to a known enum bucket. The Vue layer resolves the
     * human-readable label via RelationshipStrengthDescription
     * from the auto-generated TS enum so the mapping stays
     * single-sourced.
     */
    relationshipStrength?: RelationshipStrength | null;

    /**
     * Gets or sets the role-limit warning HTML rendered in the view
     * panel's top notification surface when one or more
     * GroupTypeRoles violate their MinCount / MaxCount against the
     * group's current active member counts. Null / empty hides the
     * notification. Populated from
     * Group.GetGroupTypeRoleLimitWarnings(out string); mirrors the
     * WebForms nbRoleLimitWarning at GroupDetail.ascx.cs:1849-1851.
     */
    roleLimitWarning?: string | null;

    /**
     * Gets or sets the friendly schedule text for the group's primary
     * schedule (e.g., "Monday at 8:00pm"). Null when the
     * group has no schedule, which hides the row.
     */
    scheduleFriendlyText?: string | null;
};
