//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/**
 * Reference to the group's parent group. Inherited Value
 * carries the parent group Id (as a string) and Text carries
 * the parent's friendly name; the picker-shaped base lets the
 * edit-mode &lt;GroupPicker&gt; bind to the same field. The
 * view-mode Overview card additionally renders a link using the
 * pre-resolved Url, which prefers the Group
 * EntityType.LinkUrlLavaTemplate (so customer-customized
 * link rules are honored) and falls back to /Group/{IdKey}.
 */
export type ParentGroupBag = {
    /** Gets or sets the category for this item. */
    category?: string | null;

    /** Gets or sets disabled for this item. */
    disabled?: boolean | null;

    /** Gets or sets the text. */
    text?: string | null;

    /**
     * Gets or sets the pre-resolved detail URL. Null / empty when
     * no link can be constructed (also during edit-mode emits, where
     * the picker overwrites Value/Text without a URL);
     * the Vue layer falls through to rendering the name as plain
     * text in either case.
     */
    url?: string | null;

    /** Gets or sets the value. */
    value?: string | null;
};
